### ISSUE TITLE
Feature Request: Books with multiple series on Audible

### ISSUE THREAD

**Issue by aterriblegamer** [seanap/Plex-Audiobook-Guide#11]
I would like to see is a book belongs to multiple series on Audible, the ability to select the series to populate into the tags.

Running into this retagging all my Tom Clancy series books. Audibles data is a hot mess. Most of the books belong to two series (one for chronological order, one for publication order) and the books are inconsistent about which series is first. This throws off all the album sort tags.

For now I am going through everything manually

**Comment by seanap** [comment]
Audible is very bad at consistency, especially in Genres, Original Release Date, Multi-series, and copyright (some titles don't have copyright info at all).  Until there is a public database like TVDB, I'm not sure how much better we can get.  My thoughts are: If it's good enough for Audible, then I guess it's good enough for me.

Right now there isn't anything that pulls the Series tag data into plex collections due to a bug in plex.  There's talks of 3rd party players that will do this, Prologue and Bookcamp.

There is no mechanism in the mp3tag scraper that will let you select which Series you want to tag the book, but in the tag review screen you can always change the series to whatever value you want.  I tend to just tag the books as they come up in Audible, then bulk edit the series for all the books to make sure they all are the same, but its a labor of love.

It would be neat if there were a second selection screen IF multiple series, where you could select or write in. Not sure I've ever seen another example of this though so I don't know if its even possible.

**Comment by aterriblegamer** [comment]
Thank you. I will close this. Another good example are Star Wars novels. Many are Labeled both with their series and Star Wars: Legends.

**Comment by seanap** [comment]
Star Wars is the absolute worst, almost worth tweeking the scr script just for those books
