### ISSUE TITLE
Plex shows all m4b files as a single album

### ISSUE THREAD

**Issue by jblyberg** [seanap/Plex-Audiobook-Guide#17]
First off, thanks for this guide, it's great.

I've got a library of about 1,000 audiobooks, all in single m4b files (with the exception of a few that are broken up). They all reside in an 'audiobooks' folder. When I create the library, Plex  lumps them under "Various Artists" in a single album with each book as a track. Have you run in to this? Thanks.

**Comment by seanap** [comment]
In the guide, I have you run my action script to move the tagged .m4b files into the correct folder structure:
`/audiobooks/Author/Book1/book1.m4b`
If you don't have the books in their own folder plex things all the tracks are for the same album.  This is because Plex supports Music libraries, so the formatting must match eg /music/artist/album/track1.mp3.
