### ISSUE TITLE
Ambiguous album name

### ISSUE THREAD

**Issue by Julian-mostert** [seanap/Plex-Audiobook-Guide#35]
hey first of thank you for the excellent work.

I have a question. when scarping can we add more to the title/ album name as this can be confusing in plex
![image](https://user-images.githubusercontent.com/10965681/135909486-4559b906-50cf-46f9-9b2e-1afe6e422467.png)
![image](https://user-images.githubusercontent.com/10965681/135909682-58ad152d-16ad-4ddf-9f54-d750380daa91.png)
![image](https://user-images.githubusercontent.com/10965681/135909787-23b8fa93-d924-4e97-aff9-934e6642aa3b.png)

So I want to get it to the full title.
Let me know if this is something I can change or if i can help here

**Comment by seanap** [comment]
I just checked my library and it looks like it does the same thing on my end for these books.  The agent is what is pulling in the title from Audible.  It would be nice if plex supported subtitles, but since they don't having the agent write both the title and subtitle would be ideal.  I'm going to move this issue over to the new agent that is being developed.

https://github.com/djdembeck/Audnexus.bundle/issues/8

**Comment by seanap** [comment]
Figured out the issue. When Local Media Assets are above Audnexus then it is using the file name. Once I moved Audnexus up then the full title gets written.

![image](https://user-images.githubusercontent.com/17012946/135926657-c45878d0-8a65-4a77-8ea9-ad8d1c948396.png)

![image](https://user-images.githubusercontent.com/17012946/135926722-058e40a0-1a0a-48d4-8b6a-0aa34a59e989.png)
