### ISSUE TITLE
LazyLibrarian

### ISSUE THREAD

**Issue by robflate** [seanap/Plex-Audiobook-Guide#5]
Just wondered if you use [LazyLibrarian](https://gitlab.com/LazyLibrarian/LazyLibrarian). If so, how does it fit into the workflow so that LazyLibrarian can still find the downloaded audiobook once the folder has been renamed/moved by this script.

Thanks for the great workflow!

**Comment by seanap** [comment]
It's been a couple years since I messed with LL.  LL is basically just an auto downloader like Sonarr, (does it also try to rename files/folders? If so, disable that)

- Have LL download to the ~/Original folder (same folder you use dl'ding manually), 
- My bash script will move the files into ~/temp where you do the mp3tag processing as outlined in the guide, 
- Then you have LL look at your ~/Audiobooks folder.

**Comment by JohanSF** [comment]
Just letting you guys know to check out Readarr ;) It's underway and will replace LL for sure. No affiliation.
