### ISSUE TITLE
Error when running mp3tag action

### ISSUE THREAD

**Issue by ladykoori** [seanap/Plex-Audiobook-Guide#70]
So, I'm trying to use the guide to set this up and got to the part  to test mp3tag by having it run the rename relocate action on an audiobook. I keep getting an error message. I've double checked and everything appears to be set up properly. Thanks!
![error screenshot](https://user-images.githubusercontent.com/4826353/159177697-c21adeb6-190c-43fa-b76b-ef3f9cf7e3fc.png)

**Comment by seanap** [comment]
In the error message it looks like you are missing a colon-slash `:\` in your audiobook folder location.

Instead of `...\GAudiobooks\...`

It should be `G:\Audiobooks\...`

If you open mp3tag, select a file, go to the Actions menu and edit your actions you can fix any typos there. See my response here https://github.com/seanap/Plex-Audiobook-Guide/discussions/66#discussioncomment-2282844

**Comment by ladykoori** [comment]
Duh....thanks. That worked.
