### ISSUE TITLE
M4B Chapters not applied

### ISSUE THREAD

**Issue by augerl** [seanap/Plex-Audiobook-Guide#80]
I'am using the auto-m4b docker container to convert my MP3 Files to a single M4B. Converting is working fine I'll get a single M4B File, but Chapters are not applied to the file.

![grafik](https://user-images.githubusercontent.com/32200952/183678537-00603091-f69a-4ecb-932a-3d9ca0926272.png)

If I want to tag the file beets-audible I am getting just a single chapter. It seems that beets is not recognizing all chapters. Or auto-m4b does not write the chapters in the right way. Chapters file looks like this:

![grafik](https://user-images.githubusercontent.com/32200952/183681547-61193bf2-8447-45c3-8909-6b072241e11f.png)

Also in Plex (but thats normal as far as I read) and Prologue I am just seeing on Chapter

Config Files are both the same as in the readme. 

Does anyone has an idea what I am doing wrong or what issue this might be?

**Comment by ElysiumFic** [comment]
There are two different ways of writing chapters: the Quicktime way (which involves creating another track to contain the data) or the Nero way.

Mp3Tag (and presumably any other app you're having that isn't recognizing the chaptering) uses Nero chaptering, and a number of apps only write chapters in Quicktime format. So likely this is your issue.

Try opening your file in MediaInfo. If, at the bottom, you see two listings of chapters, then you have the chapters in both formats. Otherwise, you only have them in one of the formats. You can check the file with AtomicParsley and this will tell you if you have a `chpl` atom (which means you have Nero chaptering) or you'll have two (or more) `trak` atoms, one of which may have a `hldr` atom beneath it that indicates it's a text track. This is where chaptering data is stored in the Quicktime way.

If you have a .cue file available, you can import it into the file using FooBar2000 and you should be able to see those chapters in Mp3Tag. I'm not sure which method Plex reads, so I'd recommend having both if you can manage it.

**Comment by augerl** [comment]
Thanks for your response. If I check the m4b file with mediainfo I'll see to Menu's wich are the chapter tags I guess. So the chapters will be applied correctly. Also when I check the file with VLC Media Player the chapters show up. Simply in Plex and Prologoue I only see the title tag of the first applied MP3 File (Kapitel 01, Track 01) instead of the chapters.
