### ISSUE TITLE
Error in AudibleDE mp3tag source for "Die Drei Fragezeichen"

### ISSUE THREAD

**Issue by gitrep3** [seanap/Plex-Audiobook-Guide#83]
Thanks for the amazing guide!

Unfortunately I encountered an issue with the following audiobook when trying to fetch tags from Audible: https://www.audible.de/pd/B0B1QKF5QZ

![image](https://user-images.githubusercontent.com/112774625/188281719-5b9bd695-4c5d-4164-a649-6ac63278ecaf.png)

I guess the reason for this is that the audiobook doesnt mention any narrator, which stops mp3tag from processing further fields

**Comment by seanap** [comment]
Hey, it turns out for that book there wasn't even an HTML section for NarratorLabel so the script was failing.  I updated the script to skip the narrator if that section wasn't fount.  I also updated the Artist tag so it doesn't put the comma and a blank space where the narrator would go.

I only tested this on two books, the one you refrenced and The Martian, so let me know if it breaks on other books.

Please download or modify your src script to the new copy https://github.com/seanap/Plex-Audiobook-Guide/blob/master/mp3tag/data/sources/Audible.de%23Search%20by%20Album.src

**Comment by gitrep3** [comment]
Thank you!! :-)
