### ISSUE TITLE
Windows version of the .sh script

### ISSUE THREAD

**Issue by gonjat** [seanap/Plex-Audiobook-Guide#9]
Hey,

I love this setup and has been great with minor flaws (not with your guide but an issue with plex and outside network).
I however was stumped on how to get the purpose of the .sh script to work on my windows setup, as I dont have audiobooks on my linux comp. There may have been a better and faster way to make this all work but here is my solution on a 100% windows setup.

Step 1. Get a program called Autohotkey and install. (very small program I have been using for years)
Step 2. Find a location you want to have this alternate script saved at, right click at the location, go to "New" in the context menu, and select "Autohotkey Script" and name it whatever you like. (leave the .ahk extention)
Step 3. Right click the newly created script, click "Edit"
Step 4. Copy and paste the code from below and change the directories to match yours, then File/Save
Step 5. Open windows task scheduler, click "Create Task", name it BookCopy or w/e, click Triggers tab, then click "New", set Begin task: to "At Logon", under advanced while in Triggers tab still, check the Repeat task every: and choose 5 minutes, set for a duration of: to Indefinitely, then click "OK. Next click the Actions Tab, then click "New", Set Action to "Start a program", then in Settings Program/script section, just point it to where ever you created this script, and then click "OK" and "OK" again.
Step 6. Log out then back in.
Step 7. Done, Enjoy!

I hope this helps, and please share an easier way if you know of one.

Code:
Copy below this line vvvvvvvvvvv
;-------------------------------------------------------------------------------------------------------

#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

CopySourcePattern := "C:\path\to\audiobook\original"  ;<----your Original folder
CopyDest := "C:\path\to\audiobook\temp"  ;<----your Temp folder

Loop, Files, %CopySourcePattern%\*, DR
{
	{
    copy_it := false
    if not FileExist(CopyDest "\" A_LoopFileName)  ; Always copy if target file doesn't yet exist.
        copy_it := true
    }	
	    if copy_it
    {
        FileCopyDir, %A_LoopFileFullPath%, %CopyDest%\%A_LoopFileName%, 1  
        if ErrorLevel
            MsgBox, Could not copy "%A_LoopFileFullPath%" to "%CopyDest%\%A_LoopFileName%".
    }
}
exitapp

**Comment by seanap** [comment]
Thank you for providing this.  I could be doing this wrong but I can't get this script to behave like my linux script.  My use case may be different than yours. Here is what I wanted to achieve with this:

- Find only files and folders added to `/original` since the last run
- Filter files to just Audiofiles (mp3 m4b ogg etc)
- Copy only the Audiofiles to `/temp`
- Ignore folderstructure, bring everything to the `/temp/*` level
- If exists do not copy again


Example:
```
/Original
-----/Book 1 (Date: T-1min)
----------book1.mp3 (Date: T-1min)
----------book1cover.jpg (Date: T-1min)
-----book2.m4b (Date: T-2min)
-----book3.m4b (Date: T-1Hr)
```

_RUN SCRIPT (every 5min)_

```
/temp
-----book1.mp3
-----book2.m4b
```

**Comment by gonjat** [comment]
Oh OK. My thoughts were slightly different I guess. Here's how it works on my end,

Script runs....

1. It loops through Original folder, gathering names of the folders, compares it to what's in the temp folder, if the temp folder does not contain the same folder name, it copies the whole folder and the contents of the folder regardless of subfolders and files.

2. When I run mp3tag, my files for that book show up, so I run the audible search, it then asks me if I want to keep original cover art, I then just say "no", when I run the bit that changes file name and moves it to the final "Audiobooks" folder, it deletes/ moves everything from the temp folder except the top level folder with the same folder name as the original.

I can tinker with my script when I have a few free mins maybe this week to get it closer to what you wanted with the .sh script. I apologize for the confusion as I didn't really account for issues with maybe the subfolders in a subfolder scenario etc. 

Where I get my audiobooks it's all in the following structure when downloaded. 

\Original
--------- \Audiobook1
-----------------------\Audiobook1.m4a
-----------------------\Audiobook1.jpg
--------- \Audiobook2
-----------------------\Audiobook2.mp3
-----------------------\Audiobook2.jpg

**Comment by gonjat** [comment]
I'm not 100% great at Linux, can you clarify how the .sh script remembers what it has already copied? I was under the impression that it went by the top level folder name of what was in the temp folder. Or does it leave a file behind containing book names or similar that it compares too?
Thanks.

**Comment by seanap** [comment]
I'm pretty sure everybody that uses this guide will have a different use case, there are no right answers.  In my particular case, my /original folder will have a mix of different top level files or folders, in all sorts of different formats, all of which need to remain untouched (no tagging, renaming, moving, or deleting).  

The reason why I have become fond of flattening the folder structure and moving only audiofiles to the top level of /temp, is that once we run the Mp3tag Action script the audiofiles will be moved to the proper archive folder structure, and nothing will be left behind in /temp.  An early version of the .sh script would copy everything, and then when I would open up /temp it would be cluttered with empty folders and .jpg's that I would then have to manually clean up.

The linux script doesn't remember what it's moved, it actually only has a very short memory.  It looks at the date modified, and only moves it if it is <= 3 min old, `-mmin -3`, the cron schedule then runs the script every 2 min so that incase something errored there will be a 1min window where it can recopy the files.

It's not perfect, there are a few edge cases that don't work.  In general though, this lets me build up queue of unprocessed books in the /temp folder.  If there are audiofiles in /temp then I know I need to tag and run the action script.

**Comment by gonjat** [comment]
Oh that's actually quite clever. I never thought of the time modified. I will definitely look more into that and make it run that way, I was going with leaving just the highest level folder and to just compare names so I didn't miss a book. I am currently working and won't have time to modify it until maybe later this week. I will update and modify my original post when I make it work like yours. Thanks for summing that up for me. I can always have the script make a txt file or cfg file, write the original audiobook name to it that it has already copied to the temp folder, and compare that way, it should never miss a book, it also wouldn't need a "window" really. I can modify the script to include a loop to run itself every x mins and you just drop it into the startup folder instead of creating a schedule for the ones that confuse easily lol.

**Comment by seanap** [comment]
That's would be awesome, there are quite a few Windows only users that would really benefit from that.  

I originally wanted to use something like `inotifywait` which would run the copy command on file creation/modification.  Since inotifywait would be always watching the folder there would be no need for a scheduler.  However, I'm using mergerfs to pool my data hdd's on my NAS, and the network share did not play nicely with inotifywait, so I just brute forced it by looking at mtime on a cron schedule.

**Comment by kcmccombs** [comment]
i was wondering if (the loop to run itself every x mins) got added to the script which i know nothing about. thanks

**Comment by seanap** [comment]
If you are referring to @gonjat 's windows autohotkey script, then he is using Windows Scheduler (Step 4) to run the script every x min.
If you are referring to my linux shell script in the guide, I use crontab to schedule the running of the script every x min.

This windows script doesn't achieve the same set of goals I needed for my setup, ymmv.

**Comment by seanap** [comment]
I updated the guide with the steps to do this with windows. I gave up trying to make a script and use a program called Dropit.  I've included my settings backup file to make install easier.  
https://github.com/seanap/Plex-Audiobook-Guide#optional-automatically-copy-untagged-audiobook-files-to-a-temp-folder
